POST http://127.0.0.1:3000/api/v1/cat HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misuu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

222
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="image"; filename="catpic.jpg"
Content-Type: image/jpeg

< ../../public/catpic.jpg
--MyBoundary--


###
GET http://127.0.0.1:3000/api/v1/cat HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/cat/48 HTTP/1.1

###
DELETE http://127.0.0.1:3000/api/v1/cat/41 HTTP/1.1
