POST http://127.0.0.1:3000/api/v1/cat HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Missuu
--MyBoundary
Content-Disposition: form-data; name="weight"

14
--MyBoundary
Content-Disposition: form-data; name="owner"

14
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="image"; filename="catpic.jpg"
Content-Type: image/jpeg

< ../../public/catpic.jpg
--MyBoundary--


###
GET http://127.0.0.1:3000/api/v1/cat HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/cat/48 HTTP/1.1

###
DELETE http://127.0.0.1:3000/api/v1/cat/658 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOTExMTExLCJuYW1lIjoidGVtZSIsInVzZXJuYW1lIjoidGVzdGl1c2VyMTIiLCJlbWFpbCI6Im1hdHRpMTIzQGdvb2dsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUzMDgxMDEsImV4cCI6MTc3NTM5NDUwMX0.G7J6kMS9kCH8HY2PEIcR6ots_2wZZimFEFr1xjVblas
PUT http://127.0.0.1:3000/api/v1/cat/44 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cat_id": 659,
    "cat_name": "Kissa",
    "weight": 6,
    "owner": 1911111,
    "filename": "vaihtui!",
    "birthdate": "2010-03-05"
}
