POST http://127.0.0.1:3000/api/v1/user HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="username"

teme1
--MyBoundary
Content-Disposition: form-data; name="user_id"

191
--MyBoundary
Content-Disposition: form-data; name="name"

teme2
--MyBoundary
Content-Disposition: form-data; name="email"

matti@masa.fi
--MyBoundary
Content-Disposition: form-data; name="role"

admin
--MyBoundary
Content-Disposition: form-data; name="password"

teme
--MyBoundary
Content-Disposition: form-data; name="image"; filename="catpic.jpg"
Content-Type: image/jpeg

< ../../public/catpic.jpg
--MyBoundary--

###
GET http://127.0.0.1:3000/api/v1/user HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/user/666 HTTP/1.1

###
POST http://127.0.0.1:3000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "user_id": 666,
    "name": "teemu",
    "username": "teme",
    "email": "teemu@testi.fi",
    "password": "passu",
    "role": "master_admin"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOTEsIm5hbWUiOiJ0ZW1lMiIsInVzZXJuYW1lIjoidGVtZTEiLCJlbWFpbCI6Im1hdHRpQG1hc2EuZmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUxMjY0MzksImV4cCI6MTc3NTIxMjgzOX0.s_uwv-yTVp7IzWAHhVLB6exTjIXhY-6zNO1CNn3jWzk
###

PUT http://127.0.0.1:3000/api/v1/user/191 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 191,
    "name": "jeemugee",
    "username": "teme",
    "email": "teemu@testi.fi",
    "password": "passu",
    "role": "master_admin"
}


###

DELETE http://127.0.0.1:3000/api/v1/user/1011112 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

