@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOTExMTEsIm5hbWUiOiJ0ZW1lIiwidXNlcm5hbWUiOiJ1c2VydGVzdDExMSIsImVtYWlsIjoibWF0dGkxMjNAZ29vZ2xlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NTMwNjczNCwiZXhwIjoxNzc1MzkzMTM0fQ.mUxK6UvXLIuEQDfNbyUmE6q4bFqZjH2PEniuNXOI6nk


POST http://127.0.0.1:3000/api/v1/user HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="username"

testiuser12
--MyBoundary
Content-Disposition: form-data; name="user_id"

1911111
--MyBoundary
Content-Disposition: form-data; name="name"

teme
--MyBoundary
Content-Disposition: form-data; name="email"

matti123@google.com
--MyBoundary
Content-Disposition: form-data; name="role"

admin
--MyBoundary
Content-Disposition: form-data; name="password"

testiuser12
--MyBoundary
Content-Disposition: form-data; name="image"; filename="catpic.jpg"
Content-Type: image/jpeg

< ../../public/catpic.jpg
--MyBoundary--

###
GET http://127.0.0.1:3000/api/v1/user HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://127.0.0.1:3000/api/v1/user/ HTTP/1.1
Authorization: Bearer {{token}}

###
POST http://127.0.0.1:3000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "user_id": 666,
    "name": "teemu",
    "username": "teme",
    "email": "teemu@testi.fi",
    "password": "passu",
    "role": "master_admin"
}

###

PUT http://127.0.0.1:3000/api/v1/user/11 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 19113,
    "name": "vaihtui",
    "username": "testita",
    "email": "teemu@testi.fi",
    "password": "passuuuu",
    "role": "admin"
}


###

DELETE http://127.0.0.1:3000/api/v1/user/11 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

